title: Matthew OBrien
remote_theme: ankitsultana/researcher@gem
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
description:
logo: https://i.ibb.co/xFFr2pN/D0-B6-EBAD-07-DF-4-B9-B-946-B-F34840555-A05.jpg
